language: "C"
seedFolders:
  - path: "/root/MetaMut/seeds"
    fileExtentions: [".c"]

programsUnderTest:
  - command: "/root/MetaMut/objects/gcc-project-trunk.obj/install/bin/gcc"
    flagsToTest:
      - flags: ["-o", "/dev/null", "-O2", "-w"]
    versionFlags:
      flags: ["-v"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.c.GccCrashDetector"

  - command: "/root/MetaMut/objects/llvm-project-trunk.obj/bin/clang"
    flagsToTest:
      - flags: ["-o", "/dev/null", "-O2", "-w"]
    versionFlags:
      flags: ["-v"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.c.ClangCrashDetector"

